### ISSUE TITLE
The source of the two batches

### ISSUE THREAD

**Issue by yzcv** [yycunc/SMNN#1]
Hi,

I am very interested in your SMNN work. But I could not figure out whether the data in your SMNN repository are synthetical or real data. And if they are real data, which dataset are they from?Could you please make it clear? Thanks a bunch!

**Comment by yycunc** [comment]
Hi,

Thanks for interesting in our method. The example we used in SMNN package is from real data. To speed up the testing process, we extracted a subset of genes and cells from the real data as example. Since the manuscript using that data is still under submission, we cannot provide the entire expression matrices currently. But for the aim of testing SMNN, these two toy batches are totally OK.
